apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: celery
  name: celery
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: celery
    spec:
      containers:
      - image: arohigupta/myproject_celery:1.0
        name: celery
        resources: {}
        volumeMounts:
        - mountPath: /myshop
          name: celery-claim0
      restartPolicy: Always
      volumes:
      - name: celery-claim0
        persistentVolumeClaim:
          claimName: celery-claim0
status: {}
