# @Author: Arohi Gupta <agupta>
# @Date:   2018-10-02T17:55:47-07:00
# @Email:  agupta@juniper.net
# @Filename: docker-compose.yml
# @Last modified by:   agupta
# @Last modified time: 2018-10-05T14:02:21-07:00

version: '3'
services:
  python:
    image: "arohigupta/myproject_python:1.0"
    container_name: app
    ports:
      - "8000:8000"
    links:
      - redis
  redis:
    image: "arohigupta/myproject_redis:1.0"
    ports:
      - "6379:6379"
  rabbitmq:
    image: "arohigupta/myproject_rabbitmq:1.0"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=contrail123
    ports:
      - "5672:5672"
  celery:
    image: "arohigupta/myproject_celery:1.0"
    links:
      - rabbitmq
