apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: python
  name: python
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: python
    spec:
      containers:
      - image: arohigupta/myproject_python:1.0
        name: app
        ports:
        - containerPort: 8000
        resources: {}
        volumeMounts:
        - mountPath: /myshop
          name: python-claim0
      restartPolicy: Always
      volumes:
      - name: python-claim0
        persistentVolumeClaim:
          claimName: python-claim0
status: {}
