apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: rabbitmq
    spec:
      containers:
      - env:
        - name: RABBITMQ_DEFAULT_PASS
          value: contrail123
        - name: RABBITMQ_DEFAULT_USER
          value: admin
        image: arohigupta/myproject_rabbitmq:1.0
        name: rabbitmq
        ports:
        - containerPort: 5672
        resources: {}
      restartPolicy: Always
status: {}
